In [11]:
import pandas as pd

In [13]:
#Placing Our input under a variqable name "dataset"

In [15]:
dataset=pd.read_csv("Salary_Data.csv")

In [17]:
#Calling to check whether our input data are memorized under the given variable dataset.

In [18]:
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [21]:
#Variable "independent" contains only the input - Years of Experience(Separated from Salary_Data.csv)

In [23]:
independent=dataset[["YearsExperience"]]

In [25]:
#Calling to verify the contents of the variable "independent"

In [27]:
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [29]:
# Saving the salary data from the given input under the variable "dependent"

In [31]:
dependent=dataset[["Salary"]]

In [33]:
# Calling to check the contents of variable dependent

In [35]:
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [37]:
# Splitting of test and training dataset with the help of sklearn library

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [41]:
#Learning phase

In [43]:
#importing the LinearRegression class from scikit-learn’s linear_model module.
#this is the machine learning model that will learn the relationship between input (X) and output (Y).
#creating an object (or instance) of the LinearRegression class, called regressor.
#This object is like a blank model — it hasn't learned anything yet.
#regressor.fit=This line trains the model (i.e., fits it to the data).
#It finds the best line that matches the pattern in your data using the training set (x_train and y_train). 
#Also after this line has been executed it is meant that "weight and Bias " had been calculated.

In [45]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [47]:
LinearRegression()

LinearRegression()

In [49]:
#Bias and weight are stored under regressor variable

In [51]:
weight=regressor.coef_

In [53]:
weight

array([[9360.26128619]])

In [55]:
bias=regressor.intercept_

In [57]:
bias

array([26777.3913412])

In [59]:
#Make Predictions (on new or test data)

In [61]:
y_pred=regressor.predict(x_test)

In [63]:
#Evaluate the Model’s Accuracy

In [65]:
# MSE (Mean Squared Error): Lower is better.
# R² Score: Tells how well your model fits the data. 1 means perfect fit, 0 means no fit.

In [67]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [69]:
r_score

0.9740993407213511

In [71]:
#Good Model:)

In [73]:
#Saving the model

In [75]:
import pickle
filename="finalized_model_linear.sav"

In [77]:
#to save this model under this filename

In [79]:
pickle.dump(regressor,open(filename,'wb'))

In [81]:

    with open("finalized_model_linear.sav", 'rb') as file:
        loaded_model = pickle.load(file)
    print("Model loaded successfully!")

Model loaded successfully!

In [83]:
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))
result=loaded_model.predict([[13]])

/Users/sairam/Desktop/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [85]:
result

array([[148460.78806172]])